import "~/styles/globals.css"
import { Toaster } from "~/components/ui/toaster"
import { Nav } from "~/components/nav"
import { ArticlePageLayout } from "~/components/articles/article-page-layout"
import { AuthProvider } from "~/modules/auth/auth.provider"

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Nav />
                    <main>
                        <ArticlePageLayout>
                            {children}
                        </ArticlePageLayout>
                    </main>
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    )
}
