import '~/styles/globals.css'
import { Inter } from 'next/font/google'
import { RefreshTokenComponent } from '~/components/refresh-token'
import { Toaster } from '~/components/ui/toaster'
import { UserContextProvider } from '~/components/user-context'
import { Nav } from '~/components/nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserContextProvider>
                    <RefreshTokenComponent />
                    <Nav />
                    {children}
                </UserContextProvider>
                <Toaster />
            </body>
        </html>
    )
}
